import Head from 'next/head'
import { Fragment } from 'react'
import CountryListing from '../components/CountryListing'
export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Country Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CountryListing />

    </Fragment>
  )
}
