import Head from 'next/head'
import { Fragment } from 'react'
export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Country Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Let`s build country finder </h1>
    </Fragment>
  )
}
